### ISSUE TITLE
"all-repos-clone" fails when it is a first application who asks fo a passphrase for a SSH key, but works later after another app asked a passphrase

### ISSUE THREAD

**Issue by AIGeneratedUsername** [asottile/all-repos#277]
# Preface

When a SSH key is used, its passphrase asked only the first time. All further access is done with a cached passphrase.

When you reboot your computer, everything repeats again: the first SSH access asks for a passphrase, then all further calls by all applications does not require a passphrase.

`all-repos-clone` fails to be this "first" application.

# Steps to be successful (to have no errors). 

My workaround:

1. Run `git clone git@gitlab.com:my/repository/path.git` in a terminal just to be asked for a passphrase for a SSH key.
2. Run `all-repos-clone` which will run now successfully without asking a passphrase for a SSH key.

# Steps to reproduce a problem
1. Reboot your OS to make sure a passphrase for a SSH key will be asked.
3. Run `all-repos-clone`.
4. You will be asked for a passphrase for a SSH key.
5. Enter a passphrase for a SSH key.
6. Get errors 
  ```
  git@gitlab.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  Error fetching /path/to/your/repo
  ```

# `all-repos.json`
```
{
  "output_dir": "/media/sam/storage/code",
  "source": "all_repos.source.gitlab_org",
  "source_settings": {
    "api_key": "<MASKED>",
    "base_url": "https://gitlab.com/api/v4",
    "archived": false,
    "org": "<MASKED>"
  },
  "exclude": ".*backend_.*",
  "push": "all_repos.push.gitlab_pull_request",
  "push_settings": {
    "api_key": "<MASKED>"
  }
}
```
# Output

Yes, I press ctrl+shift+v to paste a valid SSH key when a program asks. I believe I am not so stupid to do this wrong. At least, as I mentioned earlier, I can git clone using SSH with the same passphrase successfully from terminal.
```bash
sam@sam-rc528rc728:~$ all-repos-clone
Initializing <MASKED>/<MASKED>/backend/shared
Initialised empty Git repository in /media/sam/storage/code/<MASKED>/<MASKED>/backend/shared/.git/
Initializing <MASKED>/<MASKED>/backend/data
Initialised empty Git repository in /media/sam/storage/code/<MASKED>/<MASKED>/backend/data/.git/
Initializing <MASKED>/<MASKED>/backend/template
Initialised empty Git repository in /media/sam/storage/code/<MASKED>/<MASKED>/backend/template/.git/
Initializing <MASKED>/<MASKED>/backend/common
Initialised empty Git repository in /media/sam/storage/code/<MASKED>/<MASKED>/backend/common/.git/
Initializing <MASKED>/<MASKED>/backend/places-data
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error fetching /media/sam/storage/code/<MASKED>/<MASKED>/backend/data
Enter passphrase for key '/home/sam/.ssh/id_ed25519': 



Error fetching /media/sam/storage/code/<MASKED>/<MASKED>/backend/common




Error fetching /media/sam/storage/code/<MASKED>/<MASKED>/backend/something
Error fetching /media/sam/storage/code/<MASKED>/<MASKED>/backend/common
Traceback (most recent call last):
  File "/home/sam/.local/bin/all-repos-clone", line 8, in <module>
    sys.exit(main())
  File "/home/sam/.local/pipx/venvs/all-repos/lib/python3.8/site-packages/all_repos/clone.py", line 133, in main
    mapper.exhaust(do_map(fn, todo))
  File "/home/sam/.local/pipx/venvs/all-repos/lib/python3.8/site-packages/all_repos/mapper.py", line 16, in exhaust
    for _ in gen:
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
```

# Versions
- Lubuntu 20.04
- `pipx list` output
  ```
  venvs are in /home/sam/.local/pipx/venvs
  apps are exposed on your $PATH at /home/sam/.local/bin
     package all-repos 1.24.0, installed using Python 3.8.10
      - all-repos-clone
      - all-repos-complete
      - all-repos-find-files
      - all-repos-grep
      - all-repos-list-repos
      - all-repos-manual
      - all-repos-sed
  
  ```
- `la -la $HOME/.ssh/` output
  ```
  drwx------  2 sam sam 4096 Nov 16 15:06 .
  drwxr-xr-x 48 sam sam 4096 Feb  2 14:07 ..
  -rw-rw-r--  1 sam sam  130 Nov 16 15:06 config
  -rw-------  1 sam sam  464 Nov 15 22:07 id_ed25519
  -rw-r--r--  1 sam sam  100 Nov 15 22:07 id_ed25519.pub
  -rw-------  1 sam sam 1823 Apr 20  2022 id_rsa
  -rw-r--r--  1 sam sam  400 Apr 20  2022 id_rsa.pub
  -rw-r--r--  1 sam sam  444 Apr 21  2022 known_hosts
  ```

**Comment by asottile** [comment]
if your ssh-agent is misconfigured that's on you. perhaps you want to run ssh-add?
