### ISSUE TITLE
GitHub create pull request is failing.

### ISSUE THREAD

**Issue by serundeputy** [asottile/all-repos#320]
Hello I'm using `json_file` to try to create PRs for a subset of repos in a GitHub organization.

The repos are private. 
The token has scope repo

`all-repos-sed` creates the branch and pushes it up to GitHub, but the creating of a PR fails.

`all-repos-sed --commit-message "Update readme.md" s/Creates/This\ terraform\ module\ creates/g -- 'readme.md'`
```bash
***Errored
Traceback (most recent call last):
  File "/Users/geoffreyst.pierre/.pyenv/versions/3.10.6/envs/nimbus/lib/python3.10/site-packages/all_repos/autofix_lib.py", line 165, in repo_context
    yield
  File "/Users/geoffreyst.pierre/.pyenv/versions/3.10.6/envs/nimbus/lib/python3.10/site-packages/all_repos/autofix_lib.py", line 258, in _fix_inner
    config.push(config.push_settings, branch_name)
  File "/Users/geoffreyst.pierre/.pyenv/versions/3.10.6/envs/nimbus/lib/python3.10/site-packages/all_repos/push/github_pull_request.py", line 68, in push
    resp = make_pull_request(settings, branch_name)
  File "/Users/geoffreyst.pierre/.pyenv/versions/3.10.6/envs/nimbus/lib/python3.10/site-packages/all_repos/push/github_pull_request.py", line 61, in make_pull_request
    return github_api.req(
  File "/Users/geoffreyst.pierre/.pyenv/versions/3.10.6/envs/nimbus/lib/python3.10/site-packages/all_repos/github_api.py", line 34, in req
    resp = urllib.request.urlopen(urllib.request.Request(url, **kwargs))
  File "/Users/geoffreyst.pierre/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/geoffreyst.pierre/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/Users/geoffreyst.pierre/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/Users/geoffreyst.pierre/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/Users/geoffreyst.pierre/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Users/geoffreyst.pierre/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

all-repos.json
```json
{
  "output_dir": "ar",
  "source": "all_repos.source.json_file",
  "source_settings": {
    "filename": "repos.json"
  },
  "push": "all_repos.push.github_pull_request",
  "push_settings": {
    "api_key": "~~REDACTED~~",
    "username": "serundeputy"
  }
}
```

repos.json
```json
{
    "tf-aws-vpc": "git@github.com:GSP-Corp/tf-aws-vpc.git" 
}
```

Is this working with private repos and `json_file` for anyone else or can anyone spot what I'm doing wrong?

**Comment by asottile** [comment]
you have `.git` on the end of your url which has been unnecessary since like 2010

**Comment by serundeputy** [comment]
thanks. I've removed the `.git` from the end of the ssh url, but creating the PR still fails.

I tried changing from the ssh format to the https format, but that didn't work either (and fails to clone as it prompts for username and password and then GitHub says it does not accept username passwords any longer)

**Comment by asottile** [comment]
if it's a private repo name sure you set up your token properly including sso

**Comment by asottile** [comment]
the push happens via ssh so that doesn't tell you anything about the token

**Comment by serundeputy** [comment]
PR: https://github.com/asottile/all-repos/pull/321
