### ISSUE TITLE
Pass -e to all-repos-sed

### ISSUE THREAD

**Issue by sloria** [asottile/all-repos#66]
I tried out 

```
all-repos-sed '/sudo:/d' .travis.yml \
    --commit-msg "$(echo -e 'remove sudo: in .travis.yml\n\nhttps://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration')"
```

from https://github.com/asottile/all-repos-incantations#travis-remove-sudo

But got a failure:

```
sed: 1: ".travis.yml": invalid command code .
***Errored
Traceback (most recent call last):
  File "/Users/sloria/.pyenv/versions/3.7.0/envs/marshmallow-code/lib/python3.7/site-packages/all_repos/autofix_lib.py", line 162, in repo_context
    yield
  File "/Users/sloria/.pyenv/versions/3.7.0/envs/marshmallow-code/lib/python3.7/site-packages/all_repos/autofix_lib.py", line 221, in _fix_inner
    apply_fix()
  File "/Users/sloria/.pyenv/versions/3.7.0/envs/marshmallow-code/lib/python3.7/site-packages/all_repos/sed.py", line 40, in apply_fix
    autofix_lib.run(*sed_cmd, *filenames)
  File "/Users/sloria/.pyenv/versions/3.7.0/envs/marshmallow-code/lib/python3.7/site-packages/all_repos/autofix_lib.py", line 116, in run
    return subprocess.run(cmd, **kwargs)
  File "/Users/sloria/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('sed', '-i', '/sudo:/d', '.travis.yml')' returned non-zero exit status 1.
```

This is because my .travis.yml files have *multiple* occurrences of `sudo:`. Therefore, the `-e` option to `sed` is necessary.

Is there a way to pass additional options to `sed`? @asottile

**Comment by asottile** [comment]
I assume you're on macos?

there's a note for macos [here](https://github.com/asottile/all-repos#all-repos-sed-options-expression-filenames)

> _note_: this assumes GNU sed, if you're on osx [use `brew install gnu-sed --with-default-names`](https://stackoverflow.com/a/27595785/812183).

**Comment by sloria** [comment]
Ah, I missed that. Thanks.

Looks like the `--with-default-names` option has been removed. 

```
Warning: gnu-sed: this formula has no --with-default-names option so it will be ignored!
==> Downloading https://homebrew.bintray.com/bottles/gnu-sed-4.7.mojave.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring gnu-sed-4.7.mojave.bottle.2.tar.gz
==> Caveats
GNU "sed" has been installed as "gsed".
If you need to use it as "sed", you can add a "gnubin" directory
to your PATH from your bashrc like:

    PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
==> Summary
🍺  /usr/local/Cellar/gnu-sed/4.7: 12 files, 561KB

```

I did 

```bash
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
```

which did the trick.
